name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: git pull, build and deploy
      if: github.event.commits[0].message != 'synch'
      run: |
        echo geil,
        sshpass -p ${{ secrets.pw }} ssh root@135.181.41.34 -o StrictHostKeyChecking=no < ./deploy.bash
